Run: Forecast
     Description: Spatial IFS rainfall-runoff forecast at Mucum
     Log File: forecast.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 21 September 2026
     Last Modified Time: 22:00:00
     Last Execution Date: 23 September 2026
     Last Execution Time: 04:41:32
     Basin: Bacia Spatial LIVE 15690.7km2
     Precip: Chuva Spatial LIVE
     Control: Evento Spatial LIVE
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

