Run: Calibracao
     Description: Execucao de referencia para busca de parametros
     Log File: calibracao.log
     DSS File: Calibracao.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 September 2026
     Last Modified Time: 23:17:25
     Last Execution Date: 2 September 2026
     Last Execution Time: 23:41:42
     Basin: Bacia 86472000 13000km2
     Precip: Chuva candidata 86472000
     Control: Evento 2023-09-01 a 2023-09-10
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

