Run: Calibracao
     Description: Execucao do evento E24
     Log File: calibracao.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 September 2026
     Last Modified Time: 20:30:00
     Last Execution Date: 3 September 2026
     Last Execution Time: 10:11:30
     Basin: Bacia E24 16000km2
     Precip: Chuva E24
     Control: Evento E24
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

