Run: Calibracao
     Description: Execucao do evento E27
     Log File: calibracao.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 September 2026
     Last Modified Time: 20:30:00
     Last Execution Date: 3 September 2026
     Last Execution Time: 01:58:38
     Basin: Bacia E27 16000km2
     Precip: Chuva E27
     Control: Evento E27
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

