Run: Forecast
     Description: observed LJJ + observed Carreiro + residual rainfall
     Log File: forecast.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 10 October 2026
     Last Modified Time: 08:59:41
     Last Execution Date: 10 October 2026
     Last Execution Time: 08:59:41
     Basin: Mucum Dual Observed Boundary
     Precip: Residual Rain
     Control: Dual Control
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

