Run: Calibracao
     Description: Execucao do evento E22
     Log File: calibracao.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 September 2026
     Last Modified Time: 20:30:00
     Last Execution Date: 3 September 2026
     Last Execution Time: 18:23:58
     Basin: Bacia E22 15690.7km2
     Precip: Chuva E22
     Control: Evento E22
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

