Run: Calibracao
     Description: Execucao do evento E28
     Log File: calibracao.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 September 2026
     Last Modified Time: 20:30:00
     Last Execution Date: 3 September 2026
     Last Execution Time: 18:29:07
     Basin: Bacia E28 15690.7km2
     Precip: Chuva E28
     Control: Evento E28
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

