Run: Hindcast
     Description: G040 E1 observed-boundary research hindcast
     Log File: hindcast.log
     DSS File: output.dss
     Is Save Spatial Results: No
     Last Modified Date: 2 October 2026
     Last Modified Time: 12:16:45
     Last Execution Date: 2 October 2026
     Last Execution Time: 12:16:45
     Basin: G040 E1 Hindcast
     Precip: G040 E1 Observed Rain
     Control: E1 Control
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

